### ISSUE TITLE
Update PropertyValueEditor to use SimpleInnerContentPropertyValueEditor

### ISSUE THREAD

**Issue by mattbrailsford** [umco/umbraco-stacked-content#12]
Created SimpleInnerContentPropertyValueEditor in InnerContent package so need to update stacked content to use it, but need to release InnerContent first so we can update the nuget reference. Creating an issue to track the need to update for now.

**Comment by leekelleher** [comment]
@mattbrailsford Just to note InnerContent v1.0.3 is released. 🎉

**Comment by leekelleher** [comment]
Fixed in commit 07ba627ba3df9754dfd88de31cd10e5670ee5354
