### ISSUE TITLE
Preview doesn't seem to work for me

### ISSUE THREAD

**Issue by greystate** [umco/umbraco-stacked-content#15]
The **Disable preview** setting doesn't do anything for me. I only see the Icon + label view, no matter how the setting is set.

Do I have to do anything special (e.g. special templates/views/partials) to get previews, or is it supposed to "just work"?

I have installed **Inner Content v1.0.3** and **Stacked Content v1.0.4** in an **Umbraco v7.5.12** on Umbraco Cloud.

*I'm using Safari 10.1 on macOS 10.12.4, i.e. the latest & greatest :-)*

**Comment by mattbrailsford** [comment]
Yea, you need to create a preview view in ~/Views/Partials/Stack/ with the view named after your docktype (ie, ~/Views/Partials/Stack/MyDocTypeAlias.cshtml) or if you want one preview for all items, just create a Default.cshtml file in that location.

**Comment by greystate** [comment]
Awesome - thanks!
