### ISSUE TITLE
Removed from Our

### ISSUE THREAD

**Issue by mikkelhm** [umco/umbraco-stacked-content#18]
Hi guys

Was wondering, was the package removed from Our? or did something go wrong? all links i can find, are returning a 404 when visiting Our.

**Comment by leekelleher** [comment]
@mikkelhm Ah no, the links to Our were all preemptive.  We haven't got around to actually _releasing_ the Umbraco package yet, only the NuGet so far.

**Comment by mikkelhm** [comment]
Ahh ok, makes sense :-) ill just install from Nuget :-)

FYI, we are testing integrations with Umbraco Deploy, hopefully having it as part of the Contrib in its next release.
