### ISSUE TITLE
Link to Our Umbraco page 404s

### ISSUE THREAD

**Issue by HarveyWilliams** [umco/umbraco-stacked-content#20]
There's a link on the readme of this repo which links to https://our.umbraco.org/projects/backoffice-extensions/stacked-content but this page 404s.

Judging from #18, it looks like you never properly released this package?

Perhaps this link should be removed from the readme?

I really wanted to see some screenshots/gifs/videos of this package to see what it's all about after seeing some [mentions of it](https://twitter.com/leekelleher/status/925013263468855297) on Twitter, so I thought the Our Umbraco page would be the place to go.

**Comment by leekelleher** [comment]
Hmmm... does it still 404? https://our.umbraco.org/projects/backoffice-extensions/stacked-content

**Comment by HarveyWilliams** [comment]
@leekelleher Nope, it's fixed now. 👍

**Comment by leekelleher** [comment]
Thanks for the prompt @HarveyWilliams - it's been on our TODO list for a long time! 😃 
I'm sure we'll get people asking for support about not installing Inner Content first. 😕

**Comment by HarveyWilliams** [comment]
@leekelleher Honestly I would just ditch the Umbraco package install and focus on using the NuGet install. At least with NuGet, it ensures the user installs Inner Content as a dependency.

**Comment by HarveyWilliams** [comment]
@leekelleher Besides, I can't stand coding for the Umbraco package install - the system frequently feels broken even despite the slightly recent updates to the UI. 😢

**Comment by leekelleher** [comment]
The Umbraco package format isn't so much an issue - since we have got that all automated on build.
The issue came down to package dependencies, which of course NuGet solves nicely ... and creating projects on Our Umbraco is quite cumbersome.

Anyway, all sorted now! 🎉  Thanks again.
