### ISSUE TITLE
Check for changes before closing overlays

### ISSUE THREAD

**Issue by fraabye** [umco/umbraco-stacked-content#28]
When an editor adds content in an overlay and accidentally closes the overlay, created content might be lost without a warning. 
(Similar to this report for DTGE: https://github.com/umco/umbraco-doc-type-grid-editor/issues/52)

Would it be technically possible to add a check for changes before closing a "dirty" overlay?

**Comment by mattbrailsford** [comment]
Fixed in Inner Content commit https://github.com/umco/umbraco-inner-content/commit/954262d30befa2fa03eeeee08b28bfcef6136fd4
