### ISSUE TITLE
Umbraco Overlay is emty after updating to 7.8.x

### ISSUE THREAD

**Issue by nielslyngsoe** [umco/umbraco-stacked-content#29]
After updating to 7.8.0 and 7.8.1 I cant edit an item of Stacked Content anymore.
The overlay is basically just empty with none of the properties showing or existing in the HTML.

I hope this makes sense, and i hope you have time to look into it.

Thanks in return

**Comment by mattbrailsford** [comment]
Fixed in Inner Content this morning. You'll need to upgrade inner content to this nightly https://ci.appveyor.com/project/UMCO/umbraco-inner-content/build/1.0.4.44/artifacts

**Comment by nielslyngsoe** [comment]
YES, thanks I owe you one.
