### ISSUE TITLE
Fails to install package with SQL CE

### ISSUE THREAD

**Issue by bjarnef** [umco/umbraco-stacked-content#3]
Hi @leekelleher 

I tried to install the Umbraco package (.zip) v.1.0.3 in Umbraco 7.5.7 using SQL CE, but it fails during install.

![image](https://cloud.githubusercontent.com/assets/2919859/22085565/d8febd20-ddd4-11e6-998d-bd9edb7c20ed.png)

![image](https://cloud.githubusercontent.com/assets/2919859/22085585/e8010972-ddd4-11e6-8c8e-78dcfb8d8b00.png)

**Comment by leekelleher** [comment]
Yeah, the Umbraco package still needs some work, as it references another package dependency.

The NuGet package works, if that's an option for you?

**Comment by bjarnef** [comment]
Ahh okay, I thought the Umbraco package would install the dependency too..

Yeah, I can install it via NuGet then.. just wanted to try it out, where I find it easy just to use Umbraco packages on a demo install with SQL CE.

Maybe add a screenshot to readme? :)

**Comment by leekelleher** [comment]
Yup, the Umbraco package will add the dependency once we've wired it up. It's all still a work-in-progress, which is why we've not released it on Our yet. 😀

Good point about adding a screen grab, thanks!

**Comment by mattbrailsford** [comment]
@bjarnef it is possible to install via the zip, you just have to install the InnerContent zip manually first. Because umbraco packages don't have the concept of dependent packages this dependency currently has to be managed manually. We do have some options to make this work, it's just a question of deving them and whether they are worth while.

**Comment by greystate** [comment]
Just to confirm - I got it working by installing the InnerContent package first 🚀 

Looking forward to using this on select projects...

**Comment by mattbrailsford** [comment]
Closing issue as more a documentation issue rather than that reported.
