### ISSUE TITLE
The stack picker uses the name from the content types instead of the name template

### ISSUE THREAD

**Issue by sniffdk** [umco/umbraco-stacked-content#31]
I finally started adding more stacks to a StackedContent data type.
Was quite surprised when the picker used the name from the content types selected on the data type, as illustrated below.
![image](https://user-images.githubusercontent.com/1074004/36593498-2d55d830-189a-11e8-8bae-4380b924d485.png)

I had a talk with @mattbrailsford about the issue, and I now understand why it behaves this way.
I also understand why we can't just use the name template.
Personally, I like to prefix content types of these kinds to easily tell them apart in eg. a big ol' dropdown list, but it just looks so ugly from an editors view.

So I wonder, would it be possible to introduce an extra field to fill in the name to display when picking stacks?
Guess it would also require a custom picker dialog though? And then InnerContent would need to be able to use that dialogs custom view location.

Thoughts?

**Comment by leekelleher** [comment]
@sniffdk Thanks for raising this.

This was discussed in the early days, here: https://github.com/umco/umbraco-inner-content/pull/6
Ultimately we agreed to remain using the doc-type's name.

In my case, I was prefixing doc-type names too, but with more recent Umbraco versions, I use doc-type folders more now to organise them.

**Comment by sniffdk** [comment]
Ahh there was already an issue somewhere, great! :)

I'm using folders to organize as well, but sometimes, you get a dropdown and the folder hierarchy is no good there.
Another thing is, you can sort the selected content types on the StackedContent data type, but that sort order also isn't used in the picker.

Being able to customize the picker view would open up a lot on interesting use cases :)

**Comment by leekelleher** [comment]
I'm closing this ticket off.

Along with the conclusion from the original discussion, https://github.com/umco/umbraco-inner-content/pull/6 - we've also recently reworked how the Content Type selection works in InnerContent, (see https://github.com/umco/umbraco-inner-content/pull/23 for more details).

The UI/UX follows the Umbraco panel for creating new content nodes, displaying the Content Type's icon, name and description.
