### ISSUE TITLE
Integers render as 0 after saving

### ISSUE THREAD

**Issue by glombek** [umco/umbraco-stacked-content#34]
When you update a stacked content item with an `Umbraco.Integer` data type, it will render as 0.

`Model.Properties["myProperty"].DataValue` is correctly populated but `Model.Properties["myProperty"].Value` (and thus `Model.GetPropertyValue("myProperty")`) is 0.

Refreshing the page will fix the problem, rendering the view before editing renders correctly also.

**Comment by leekelleher** [comment]
@glombek - is this on the frontend or in the backoffice preview?

**Comment by glombek** [comment]
In the backoffice preview, Umbraco 7.8.1. Only after you edit the number, initial load of the previews is fine.

**Comment by leekelleher** [comment]
@glombek Just to let you know, I can reproduce the bug.  I don't currently have an estimate when it'll be fixed, but feedback that it's reproducible.

**Comment by leekelleher** [comment]
@glombek Here's my proposed workaround - _as in this is what I'd do for my own website implementations._

De-register Umbraco's own `` and replace it with my own custom version that can handle the `Int64` (`long`) value-types.

```csharp
using System;
using Umbraco.Core;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Core.PropertyEditors;
using Umbraco.Core.PropertyEditors.ValueConverters;

namespace Our.Umbraco.StackedContent.Web.HotFixes
{
    public class MyApplicationEventHandler : ApplicationEventHandler
    {
        protected override void ApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            PropertyValueConvertersResolver.Current.RemoveType<IntegerValueConverter>();
        }
    }

    public class MyIntegerValueConverter : IntegerValueConverter
    {
        public override object ConvertDataToSource(PublishedPropertyType propertyType, object source, bool preview)
        {
            if (source is long value)
                return Convert.ToInt32(value);

            return base.ConvertDataToSource(propertyType, source, preview);
        }
    }
}
```

I hope this helps?

**Comment by leekelleher** [comment]
Update: I've submitted a patch for Umbraco: https://github.com/umbraco/Umbraco-CMS/pull/2500

**Comment by glombek** [comment]
Oh wow! Brilliant thanks!

**Comment by leekelleher** [comment]
Closing ticket, workaround supplied, (patch for Umbraco submitted).
