### ISSUE TITLE
Use ConfigureForDisplay to hideLabel

### ISSUE THREAD

**Issue by mattbrailsford** [umco/umbraco-stacked-content#37]
I'm not sure if we are hiding the label if someone selects to hide it in the prevalue. Either way, we should be using `ConfigureForDisplay` like we do in nested content https://github.com/umco/umbraco-nested-content/blob/develop/src/Our.Umbraco.NestedContent/PropertyEditors/NestedContentPropertyEditor.cs#L105

**Comment by leekelleher** [comment]
Wondering if this is one of those that could belong in Inner Content?
No pressure on that, just a passing thought.

**Comment by mattbrailsford** [comment]
I did ponder that myself. I think for the time being I'm happy to leave IC as just managing anything to do with content types as otherwise it could become a dumping ground for "useful" functions.
