### ISSUE TITLE
Item number not updating when reordering

### ISSUE THREAD

**Issue by stvnhrlnd** [umco/umbraco-stacked-content#39]
When a name template is not supplied Inner Content uses the template `Item {{$index+1}}`, however this isn't reflected on the UI when the order is changed:

![stacked-content-reorder](https://user-images.githubusercontent.com/12008315/38270086-4cf7d96e-377a-11e8-8dd3-5fd42c109023.gif)

I've looked into this and I noticed that the UI.Sortable `update` callback is used to populate the names (see [this line](https://github.com/umco/umbraco-stacked-content/blob/develop/src/Our.Umbraco.StackedContent/Web/UI/App_Plugins/StackedContent/js/stackedcontent.controllers.js#L49)). If you put a breakpoint in that callback you'll see that it's called _before_ the model is updated, so the underlying array hasn't been reordered yet. Using the `stop` callback instead seems to fix it, although I've not tested rigorously.

**Comment by leekelleher** [comment]
@stvnhrlnd Thanks for raising this.  I've given the `stop` callback a try, that appears to work well.

Did you want to submit a PR?
(I could make the code change, but would rather give you the opportunity to contribute 🥇)

**Comment by stvnhrlnd** [comment]
@leekelleher PR submitted :)
