### ISSUE TITLE
Disable the Preview?

### ISSUE THREAD

**Issue by leekelleher** [umco/umbraco-stacked-content#4]
With my current site implementation, we're not using the preview feature - the "wireframed preview" (e.g. icon + title) is sufficient.  However calls to `scResources.getPreviewMarkup` are still being made.

(It adds considerable load/render time when you have several content blocks)

Would we consider having an option to disable (attempting) to render a preview?

**Comment by mattbrailsford** [comment]
Sounds good to me. Prevalue option?

**Comment by leekelleher** [comment]
Yup - as a prevalue option.

I'm happy to give dev'ing it a try, just wanted to check first 😉

**Comment by mattbrailsford** [comment]
Go for it :)

**Comment by leekelleher** [comment]
![monkey](https://media1.giphy.com/media/cegWQ66TiGYDK/100.gif)

**Comment by leekelleher** [comment]
Closing. Opened PR #5
