### ISSUE TITLE
Stacked Content overlaps tab overflow menu

### ISSUE THREAD

**Issue by stvnhrlnd** [umco/umbraco-stacked-content#41]
Interesting one as it can be fixed in either Stacked Content or Umbraco itself. Here's a screenshot:

![stacked_content_overlap](https://user-images.githubusercontent.com/12008315/38390233-9a6978d4-3918-11e8-8eca-f71b039122b4.png)

The issue is that both `.stack__item` and `.umb-nav-tabs` have a `z-index` of 10, so Stacked Content appears on top because it comes later in the markup.

I've created an Umbraco issue and PR to raise the `z-index` value for `.umb-nav-tabs` but I figured it'd be a good idea to decrease `.stack__item` to 9 so that it's fixed in previous versions of Umbraco.

More info: http://issues.umbraco.org/issue/U4-11185

**Comment by stvnhrlnd** [comment]
PR: https://github.com/umco/umbraco-stacked-content/pull/42

**Comment by leekelleher** [comment]
Thanks @stvnhrlnd - I'll give PR #42 a try 👍 

I'll close this ticket off and comment over on PR #42
