### ISSUE TITLE
Related links picker doesn't fit within the dialog

### ISSUE THREAD

**Issue by drpeck** [umco/umbraco-stacked-content#46]
The Umbraco.RelatedLinks2 picker uses a table layout which extends outside of the editable area in a dialog. 

I appreciate that there is no action that you can take (within the scope of Stacked Content) to update the picker HTML to allow it to fit, however I thought I would log it.

The only solution that I can think of is to set `overflow: scroll`. It's possible that you'll have a better idea.

**Comment by leekelleher** [comment]
Hi @drpeck. I'm closing this one off, as it's not a Stacked Content bug per se, more that it's unfortunate that the Related Links UI is too wide, (or that the overlay modal is too narrow?)  Either way, it'd be an Umbraco core fix.

Thanks for raising it, I appreciate that different editor UIs can be frustrating.
