### ISSUE TITLE
Back-office preview not rendering RTE Macro

### ISSUE THREAD

**Issue by AndyFelton** [umco/umbraco-stacked-content#55]
When rendering a Document Type which has a Rich Text Editor Data Type containing a Macro I get an Error indicating 'Cannot render a macro when there is no current PublishedContentRequest'.

See our issue https://our.umbraco.com/packages/backoffice-extensions/stacked-content/stacked-content-feedback/94950-macros-stacked-content#comment-300280 for more information.

**Comment by AndyFelton** [comment]
@leekelleher I've used the code I'd found previously and have running on my API controller to create the  PublishedContentRequest and created a pull request - may need some additional work before merging
Pull Request #57

**Comment by leekelleher** [comment]
Closing this one, fixed in PR #57.  It'll be part of upcoming v2.0.2 release, (TBC).

**Comment by leekelleher** [comment]
I'll try to get a release out tomorrow, otherwise it'd be next week.

In the meantime, there are CI builds on MyGet and AppVeyor...

https://www.myget.org/feed/umbraco-packages/package/nuget/Our.Umbraco.StackedContent

https://ci.appveyor.com/project/UMCO/umbraco-stacked-content/build/artifacts
