### ISSUE TITLE
Back Office Render of Data Type with dropdown

### ISSUE THREAD

**Issue by AndyFelton** [umco/umbraco-stacked-content#56]
Hi guys,

I've got a drop down configured as one of my properties on a Data Type. When doing a back office preview the GetPropertyValue for the property will return an object of type Newtonsoft.Json.Linq.JArray containing the  id on the Pre Value was expecting a string (or array of to support multiple selects) of value. 

**Settings**
Windows 10
Visual studio 2017
Umbraco 7.12.3 (installed via nuget)
Stacked content - 1.0.4 (installed via nuget)
(No starter kit)

If you want me to create a minimal project showing the issue let me know.

Thanks
Andy

**Comment by leekelleher** [comment]
@AndyFelton Which dropdown editor is it? Is it "Umbraco.DropDown.Flexible"?

From what I recall, using the dropdown value on the frontend did return the prevalue ID, not the value itself. But then I'd expect the dropdown's PropertyValueConverter to handle that part. 🤔

**Comment by leekelleher** [comment]
Good news is that I'm able to reproduce this issue, as in it shows a JSON/prevalue ID in the back-office preview, but on the frontend it renders the correct the value.  I'm still investigating, will report back later.

**Comment by leekelleher** [comment]
Bad news is that the "Umbraco.DropDown.Flexible" editor does the switch from prevalue ID to text value when the page/node is saved to the database.  The downside here is that Stacked Content's preview is using the "editor value" not the "database value", meaning any prevalue-based editor isn't going to work nicely with the preview. Bah! 😖 

---

@mattbrailsford, can you recall if we've hit this issue before, (e.g. calling the `ConvertDbTo{X}` methods)? I checked Mortar, but we ended up disabling back-office previews. Don't think we've done any other property-editors with previews.

**Comment by leekelleher** [comment]
@AndyFelton At the moment, the best thing to do is work around the issue by dealing with the prevalue ID directly in your preview partial-view.

You could either deserialize the `JArray` and parse out the `int`, or do a rough & ready string char removal...
e.g.
```cshtml
@{
    var value = Model.Content.GetPropertyValue<string>("whatever");
    var id = int.Parse(value.Trim('[', '\r', '\n', ' ', '"', ']'));
}
@Umbraco.GetPreValueAsString(id)
```

**Comment by AndyFelton** [comment]
Hi Lee,

Sorry been out in meetings today. I’m OK with that as a workaround and have implemented something similar yesterday.

As always thanks for looking at this.

**Comment by leekelleher** [comment]
I'll close off this ticket for now, as looking into full supporting this properly is a considerable amount of work, (ultimately it exposes how much of a "hack" that these types of editors are within Umbraco).

Given the workaround works, (and is isolated to the preview partial-view), it's a manageable solution for now.
