### ISSUE TITLE
Changing the width of editor pane using a custom style sheet

### ISSUE THREAD

**Issue by NikRimington** [umco/umbraco-stacked-content#61]
Okay, so here is a recap of a discussion had with @leekelleher based on an existing discussion on the Our forum (https://our.umbraco.com/packages/backoffice-extensions/stacked-content/stacked-content-feedback/91293-change-width-of-editor-pane-overlay)

The idea:

Have Stacked/Inner content apply a class that is unique-ish to the editor pane. My initial proposal was allow for an identifiable class to be set when defining the stacked content property editor so each editor could have a different width pane as appropriate.

This could then allow a dev to use a custom style sheet to contain all defined widths for the pane... e.g. StackedContent-Programme - Umb-Overlay could be set to 50% width, but StackedContent-PageBuilder - Umb-Overlay could be set to 75% width. All configured the devs custom CSS file (so Stacked/Inner can be upgraded without overriding these stylesheets).

After the discussion with Lee, it was thought that maybe using the doctype alias as the class might work but it does mean that every stacked content overlay would be impacted by the style change so you couldn't have it different for each use case. So another option is to include the property alias into the class automatically as well. These options would mean that there wouldn't be a config setting but the class(es) would be generated automatically.

**Comment by leekelleher** [comment]
@NikRimington I've added a branch to Inner Content for this enhancement.
https://github.com/umco/umbraco-inner-content/pull/42

**Comment by leekelleher** [comment]
Closing this ticket off. Further discussion can be had over at https://github.com/umco/umbraco-inner-content/pull/42.

**Comment by NikRimington** [comment]
Amazing :-) You guys are awesome!
