### ISSUE TITLE
Back-office preview breaks when RTE has hyperlinks version 2.0.2

### ISSUE THREAD

**Issue by Simon-Ratcliffe-Epiphany** [umco/umbraco-stacked-content#62]
Hi, I have a bug related to the latest version of stacked content (version 2.02). It is sort of linked to a previous issue (Back-office preview not rendering RTE Macro #55) so apologies if I should have added it to that ticket.

After installing the latest version of stacked content (moving from 2.01) to try and fix an issue with rendering RTE macros I started seeing more errors with the back-office preview. Rather than seeing our custom markup I have been seeing the default grey boxes. After further investigation this looks to be an issue with any RTE that has hyperlinks. If I remove the hyperlinks the preview shows our custom markup. 

Also, I still can't get the back office preview to work with a RTE Macro. In terms of code we create our own front end view models and map the models builder models. For the RTE we are casting to a string calling ToString().

Any help would be appreciated.

**Comment by leekelleher** [comment]
@Simon-Ratcliffe-Epiphany Thanks for raising this. I'll close off this ticket and review PR #63. I assume @rustybox is working with you on this?

**Comment by Simon-Ratcliffe-Epiphany** [comment]
Correct, we are both working on the same site.
