### ISSUE TITLE
Icon alias conflict

### ISSUE THREAD

**Issue by skartknet** [umco/umbraco-stacked-content#67]
There's an issue affecting Iconic when is used inside a stacked content. If the doctype used in the stacked content has a Iconic property with alias 'icon' it conflicts with the doctype icon.
I have checked the database and the value stored for the stacked content in the Iconic property is correct. , the $scope.model.value that Iconic controller retrieves is the Icon used for the doctype instead the actual Iconic value.
Not sure if it's an Iconic, Stacked content or Umbraco issue. Any ideas?

**Comment by leekelleher** [comment]
Hi @skartknet, ah yes, the use of "icon" as a property-alias is [a known issue with InnerContent](https://github.com/umco/umbraco-inner-content#known-issues) (the library that powers StackedContent). It's one of our reserved words. The other ones are: "`name`", "`key`", "`children`" and "`icon`".

I'll add link this up with the known issues on StackedContent too.

**Comment by skartknet** [comment]
Well, at least it's a known issue ;) thanks!
